# Generated by Django 5.1.5 on 2025-01-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('shortened_url', models.CharField(max_length=50, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_password_protected', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='url_shortener.url')),
            ],
        ),
    ]
